apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytomcat-stag-deployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector: 
    matchLabels:
      app:  tomcat-stag-frontend
  template:
    metadata:
      name: myPod
      labels:
        app:  tomcat-stag-frontend
    spec:
      containers:
      -  name: myweb
         image: priya9soni/appimage:v1 
         imagePullPolish: Always
         ports:
         - containerPort: 80

